### ISSUE TITLE
Allow data flow specification with config files

### ISSUE THREAD

**Issue by aemaem** [aemaem/litfass#4]
* YAML configuration file
```
collection:
    name: foo
    transformation: return input
...
```
* Transformation is done via Kotlin scripts: https://kotlinexpertise.com/run-kotlin-scripts-from-kotlin-programs/
